### ISSUE TITLE
getting java.lang.NullPointerException

### ISSUE THREAD

**Issue by noozan** [jcustenborder/kafka-connect-examples#4]
i ma using jms connector

```
connector.class=io.confluent.connect.jms.JmsSourceConnector
transforms.messageField.field=test
transforms.FromXml.type=com.github.jcustenborder.kafka.connect.transform.xml.FromXml$Value
confluent.topic.bootstrap.servers=localhost:9092
java.naming.factory.initial=org.jnp.interfaces.NamingContextFactory
transforms=messageField,FromXml
java.naming.provider.url=jnp://<url>:<port>
jms.destination.name=requestQueue
java.naming.factory.url.pkgs=org.jboss.naming:org.jnp.interfaces
transforms.FromXml.schema.path=http://localhost:3030/fdd/config/FUNSTRANSFER.xsd
confluent.topic.replication.factor=1
name=test
kafka.topic=test_topic
transforms.messageField.type=org.apache.kafka.connect.transforms.ExtractField$Value
```

i am getting the following exception

> org.apache.kafka.connect.errors.ConnectException: java.lang.NullPointerException
> 	at org.apache.kafka.connect.runtime.ConnectorConfig.transformations(ConnectorConfig.java:259)
> 	at org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:496)
> 	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:452)
> 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:865)
> 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:110)
> 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$12.call(DistributedHerder.java:703)
> 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$12.call(DistributedHerder.java:684)
> 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:270)
> 	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:219)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException
> 	at com.github.jcustenborder.kafka.connect.transform.xml.XSDCompiler.compileContext(XSDCompiler.java:156)
> 	at com.github.jcustenborder.kafka.connect.transform.xml.FromXml.configure(FromXml.java:120)
> 	at org.apache.kafka.connect.runtime.ConnectorConfig.transformations(ConnectorConfig.java:256)
> 	... 13 more

without the transformation it is working just fine. but i was to convert xml data in text field to avro

**Comment by jcustenborder** [comment]
@noozan Basically what happened here is the transform cannot compile the xsd. Would you be able to share the xsd and example data?

**Comment by noozan** [comment]
thank you @jcustenborder 

here is the xsd

```
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

 <!--
 XML Schema Generated from XML Document on Tue Aug 27 2019 13:03:34 GMT+0500 (Pakistan Standard Time) 
-->
 <!--
 with XmlGrid.net Free Online Service http://xmlgrid.net 
-->
<xs:element name="tns:FundsTransferIZS">
<xs:complexType>
<xs:sequence>
<xs:element name="tns:eventCommon">
<xs:complexType>
<xs:sequence>
<xs:element name="ns0:application" type="xs:string"/>
<xs:element name="ns0:companyId" type="xs:string"/>
<xs:element name="ns0:operator" type="xs:string"/>
<xs:element name="ns0:today" type="xs:date"/>
<xs:element name="ns0:transactionStage" type="xs:string"/>
<xs:element name="ns0:eventId" type="xs:string"/>
<xs:element name="ns0:creationTime" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="tns:id" type="xs:string"/>
<xs:element name="tns:transactionType" type="xs:string"/>
<xs:element name="tns:creditCustomer" type="xs:int"/>
<xs:element name="tns:creditAcctNo" type="xs:int"/>
<xs:element name="tns:creditCurrency" type="xs:string"/>
<xs:element name="tns:creditValueDate" type="xs:date"/>
<xs:element name="tns:externalRef" type="xs:string"/>
<xs:element name="tns:narrativeLn1" type="xs:string"/>
<xs:element name="tns:narrativeLn3" type="xs:string"/>
<xs:element name="tns:amountCredited" type="xs:string"/>
</xs:sequence>
<xs:attribute name="xmlns:tns" type="xs:string"/>
<xs:attribute name="xmlns:xsi" type="xs:string"/>
<xs:attribute name="xmlns:ns0" type="xs:string"/>
<xs:attribute name="xsi:schemaLocation" type="xs:string"/>
</xs:complexType>
</xs:element>
</xs:schema>
```

Example data

```
VALUE

priority 4
timestamp 1566967365310
text <?xml version="1.0" encoding="UTF-8"?><tns:FundsTransferIZS xmlns:tns="http://www.temenos.com/T24/event/Notification/FundsTransferIZS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.temenos.com/T24/event/Notification/FundsTransferIZS Notification-FundsTransferIZS.xsd" xmlns:ns0="http://www.temenos.com/T24/event/Common/EventCommon"><tns:eventCommon><ns0:application>FUNDS.TRANSFER</ns0:application><ns0:companyId>MV0017796</ns0:companyId><ns0:operator>IZS</ns0:operator><ns0:today>2019-04-02</ns0:today><ns0:transactionStage>INPUT-AUTHORISE</ns0:transactionStage><ns0:eventId>9380299d-0074-41f7-b092-00rrv4443</ns0:eventId><ns0:creationTime>2019-08-28T04:42:43.6986624Z</ns0:creationTime></tns:eventCommon><tns:id>FT190923MM6N</tns:id><tns:transactionType>AC</tns:transactionType><tns:creditCustomer>111111</tns:creditCustomer><tns:creditAcctNo>771111111</tns:creditAcctNo><tns:creditCurrency>MVR</tns:creditCurrency><tns:creditValueDate>2019-04-02</tns:creditValueDate><tns:externalRef>xxx70684</tns:externalRef><tns:narrativeLn1>28-08-2019 09-42-41</tns:narrativeLn1><tns:narrativeLn3>Internet Banking</tns:narrativeLn3><tns:amountCredited>MVR0.10</tns:amountCredited></tns:FundsTransferIZS>
deliveryMode 2
messageType text
properties { }
redelivered false
messageID ID:JBM-b2d7d292-a9b9-4aa1-b369-8402a9e49ad7
type T24_INTEGRATION_EVENTS
expiration 0
destination { destinationType: queue, name: requestQueue }
correlationID 1566967365.2951487_10
```

**Comment by noozan** [comment]
@jcustenborder any update

**Comment by jcustenborder** [comment]
@noozan That's not a valid xsd. Basically in code I'm compiling the schema to code and augmenting the code. Easy way to look at it is to use `xjc fundstransfer.xsd`. Take a look at this [branch](https://github.com/jcustenborder/kafka-connect-transform-xml/tree/issue-16). This does a better job printing the error messages.
```
parsing a schema...
[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:FundsTransferIZS' is not a valid value for 'NCName'.
  line 10 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'attribute'. Recorded reason: cvc-datatype-valid.1.2.1: 'xmlns:tns' is not a valid value for 'NCName'.
  line 37 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-attribute.3.1: One of 'ref' or 'name' must be present in a local attribute declaration.
  line 37 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'attribute'. Recorded reason: cvc-datatype-valid.1.2.1: 'xmlns:xsi' is not a valid value for 'NCName'.
  line 38 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-attribute.3.1: One of 'ref' or 'name' must be present in a local attribute declaration.
  line 38 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'attribute'. Recorded reason: cvc-datatype-valid.1.2.1: 'xmlns:ns0' is not a valid value for 'NCName'.
  line 39 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-attribute.3.1: One of 'ref' or 'name' must be present in a local attribute declaration.
  line 39 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'attribute'. Recorded reason: cvc-datatype-valid.1.2.1: 'xsi:schemaLocation' is not a valid value for 'NCName'.
  line 40 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-attribute.3.1: One of 'ref' or 'name' must be present in a local attribute declaration.
  line 40 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-must-appear: Attribute 'name' must appear in element 'element'.
  line 10 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:eventCommon' is not a valid value for 'NCName'.
  line 13 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'ns0:application' is not a valid value for 'NCName'.
  line 16 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 16 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'ns0:companyId' is not a valid value for 'NCName'.
  line 17 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 17 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'ns0:operator' is not a valid value for 'NCName'.
  line 18 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 18 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'ns0:today' is not a valid value for 'NCName'.
  line 19 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 19 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'ns0:transactionStage' is not a valid value for 'NCName'.
  line 20 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 20 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'ns0:eventId' is not a valid value for 'NCName'.
  line 21 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 21 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'ns0:creationTime' is not a valid value for 'NCName'.
  line 22 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 22 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 13 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:id' is not a valid value for 'NCName'.
  line 26 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 26 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:transactionType' is not a valid value for 'NCName'.
  line 27 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 27 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:creditCustomer' is not a valid value for 'NCName'.
  line 28 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 28 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:creditAcctNo' is not a valid value for 'NCName'.
  line 29 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 29 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:creditCurrency' is not a valid value for 'NCName'.
  line 30 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 30 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:creditValueDate' is not a valid value for 'NCName'.
  line 31 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 31 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:externalRef' is not a valid value for 'NCName'.
  line 32 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 32 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:narrativeLn1' is not a valid value for 'NCName'.
  line 33 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 33 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:narrativeLn3' is not a valid value for 'NCName'.
  line 34 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 34 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] s4s-att-invalid-value: Invalid attribute value for 'name' in element 'element'. Recorded reason: cvc-datatype-valid.1.2.1: 'tns:amountCredited' is not a valid value for 'NCName'.
  line 35 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd

[ERROR] src-element.2.1: : One of 'ref' or 'name' must be present in a local element declaration.
  line 35 of file:/Users/jeremy/source/opensource/kafka-connect/transforms/kafka-connect-transform-xml/src/test/resources/com/github/jcustenborder/kafka/connect/transform/xml/fundstransfer.xsd
```

**Comment by inash** [comment]
Is JDK an explicit requirement to use this connector?

**Comment by jcustenborder** [comment]
Kafka requires JDK8 +

**Comment by inash** [comment]
I meant the JDK and not just the JRE. The XSDCompiler doesn't seem to work if running on only JRE.

**Comment by jcustenborder** [comment]
Ahh yes sorry it will require a full JDK vs JRE. XSDCompiler generates a java class and compiles it.
